# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GxEScanC <- function(phenotype, covariates, index, geneticData, outFilename, skippedFilename, minmaf) {
    .Call('_GxEScanR_GxEScanC', PACKAGE = 'GxEScanR', phenotype, covariates, index, geneticData, outFilename, skippedFilename, minmaf)
}

